<?php
$MenuBio = "Biography";
$MenuDisco = "Discography";
$MenuAwards = "Awards & Affiliations";
$MenuContact = "Contact";
$PageTitle = 'Biography';
$PageDescription = "Biographie d'Andre Perry :: Créateur du Studio (Morin-Heights), premier studio d'enregistrement à équipement perfectionné de calibre mondial installé dans un environnement propice à la créativité et largement reconnu comme l'un des membres les plus importants de l'industrie canadienne de la musique";
$PageKeywords = 'Andre Perry, Biographie Andre Perry, Andre Perry studio, le studio, normedia';
//
$PageContent = '
<p><a href="/biography/photos/present-andre.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/present-andre-tb.jpg" alt="Andre Perry Ca. 1956" width="100" height="92" /></a>Andr&eacute; Perry is President and founding partner of Fidelio Technologies Inc. <a target="_blank" href="http://www.fideliotechnologies.com">www.fideliotechnologies.com</a>
The company has developed 2xHD, a proprietary system for the transformation of analog and digital music masters into high resolution DXD and DSD formats, and their derivatives, 88/24 and higher formats for downloading on HD audio sites around the world. Fidelio Technologies also acts as a download licensee for various labels.
</p>Widely acknowledged as a pillar of the Canadian Music Industry, producer, musician, composer, recording engineer, Andr&eacute; Perry is the creator and founder of, the first sophisticated, world-class environmental recording facility; Le Studio (Morin Heights).  Over 250 million copies of recordings made at Le Studio have been sold world-wide.</p>

	<p><a name="1960" id="1960"></a><img src="/biography/1960-1970.gif" alt="1960 - 1970" width="118" height="25" /></p>
	<p><a class="FloatRight" href="/biography/photos/Andre_Perry-1956.jpg" data-lightbox="roadtrip"><img src="/biography/photos/Andre_Perry-1956.jpg"  width="100" height="66" ></a>Born in Montreal, Canada, in 1937, Perry started his career as jazz drummer and singer when he was 16. By the age of 20 Perry was in demand as a studio musician and headed his own jazz group, winning the Grand Prix du Disque Canadien for most promising new male recording artist of the year in 1962.</p>

<p><a href="/biography/photos/3.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/3tn.jpg" alt="Ca. 1962" width="100" height="73" /></a><a href="/biography/photos/4.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/4tn.jpg" alt="1967 - Studio d&rsquo;enregistrement" width="100" height="73" /></a>Perry opened his first recording facility in 1962 - Studio Andr&eacute; Perry - located in the Montreal suburb of Ville Brossard. </p>
<p><a href="/biography/photos/5.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/5tn.jpg" alt="Andre Perry :: Jean-Pierre Ferland" width="100" height="73" /></a>Since the  very early years, Perry&rsquo;s passion for excellence attracted most of Quebec&rsquo;s artists to his  studio. "His significant contributions to  the emerging careers of the leaders of the fledgling industry enhanced his  reputation; "<strong>Jean-Pierre Ferland&rsquo;s</strong> career building signature albums "<strong><em>Jaune</em></strong>"  and "<strong><em>Soleil</em></strong>"  were produced and recorded by Perry and are still considered musical landmarks  in French Canada. In February 2008, in a  survey made by Montreal&rsquo;s premier newspaper <strong>La Presse, </strong>of the best albums released by Quebec artists over the  past 50 years,<strong> Ferland&rsquo;s </strong>album <strong>Jaune</strong> and <strong>Robert Charlebois&rsquo;</strong> album <strong>"Lindbergh"</strong>which was also produced &amp;  recorded by Perry during the same period, were voted number 1 and number 2  respectively. A similar poll made  earlier by Montreal&rsquo;s  cultural news weekly, <strong>Voir</strong>, produced  the same results.</p>
<p><a href="/biography/photos/5b.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/5btn.jpg" alt="Premi&egrave;re console num&eacute;rique" width="100" height="70" /></a><a href="/biography/photos/6.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/6tn.jpg" alt="Magn&eacute;tophones (Le Moog)" width="100" height="60" /></a>Because of his thirst for new vistas &amp; constant search for the latest technology, Perry&rsquo;s studio was first in Canada to make use of the most up-to-date tools such as: &nbsp;a transistorized console, the first synthesizer (the <strong>Moog</strong>), first multi-track recorders, and so on. His innovations and reputation made him the obvious choice for special projects. &nbsp;Both the governments of Canada and of Qu&eacute;bec selected Perry to produce the multi-media presentations for their respective Expo &rsquo;67 host pavilion.&nbsp; The organizing committee of the Olympic Games (COJO) asked him to produce the music of the opening &amp; closing ceremonies for the <strong>1976 Montreal Olympic Games</strong>. The <strong>Grands Ballets Canadiens</strong>, called on his services to create a unique, multi-channel playback environment for their performance of the Who&rsquo;s rock opera &lsquo;Tommy&rsquo; at Montreal&rsquo;s Place des Arts and choreographer <strong>Eddy Toussaint</strong> commissioned him to compose and produce original electronic music for his ballet company. </p>
<p><a href="/biography/photos/LENNON-4.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/LENNON-41.jpg" alt="John Lennon single" width="100" height="94" /></a></p>
<p>In 1969 <strong>John Lennon </strong>and <strong>Yoko Ono</strong> came to Montreal and invited the world to their &lsquo;Bed-In&rsquo; for Peace.  On the last day, Perry was asked to record what has since become a most famous anthem: &lsquo;<strong>Give Peace a Chance</strong>&rsquo;.  In appreciation for his additions in post- production and flair in the final mix, Lennon generously included Perry&rsquo;s complete address on the record label &ndash; an unprecedented and never reproduced gesture.  In the spring 2009, on the 40th anniversary of the event, the <strong>Montreal Museum of Fine Arts</strong>, with the cooperation of Yoko Ono, celebrated the happening with the creation of a very successful exhibition, which featured memorabilia from the &lsquo;Bed-In&rsquo; and the recording, Yoko&rsquo;s memoires and artworks, and some of Perry&rsquo;s contributions.  A record number of viewers visited the exhibition.</p>
<table width="100%" border="0" cellpadding="10">
	<tr>
		<td align="center"><a href="/biography/photos/7.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/7tn.jpg" alt="Enregistrement de Give Peace a Chance de John Lennon" width="100" height="71" /></a></td>
		<td align="center"><a href="/biography/photos/Yoko Montreal_096[1].JPG" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Yoko-Montreal_096_tn.jpg" alt="" width="100" height="71" /></a></td>
		<td align="center"><a href="/biography/photos/John_Lennon-Yoko_Ono.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/John_Lennon-Yoko_Ono.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
</table>
<p style="margin-top:20px;"><a name="1970" id="1970"></a><img src="/biography/1970-1974.gif" alt="1970-1974" width="118" height="25" /></p>
<p><a href="/biography/photos/8.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/8tn.jpg" alt="Studio-dans-l&rsquo;&eacute;glise" width="100" height="145" /></a><a href="/biography/photos/9.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/9tn.jpg" alt="Dans l&rsquo;&eacute;glise" width="100" height="67" /></a>Perry acquired an Anglican church on Amherst Square in downtown Montreal and moved his facility there.&nbsp; In early 1970, prior to the digital era, he persuaded the multi-national Ampex Corp. to develop and manufacture a locking device to synchronize several multi-track recorders, expanding the range from 16 to 32 tracks.&nbsp; </p>
<p><a href="/biography/photos/10.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/10tn.jpg" alt="Studio A" width="100" height="69" /></a>Perry sold the studio-in-the-church in 1972 to devote his time to producing records and running his new company, <strong>Good Noise Records</strong>, associating with New York&rsquo;s <a href="/biography/photos/11.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/11tn.jpg" alt="Ctrl. Room A" width="100" height="74" /></a>bubbling underground music scene, collaborating with Tony Levin, David Spinozza, John Lissauer, the Brecker Brothers.</strong>&nbsp; Good Noise Records released recordings by <strong>Alan Gerber, Anna McGarrigle, Ronney Abramson, Tim Ryan, Man Made, The Hotel Orchestra and Brian Blain.</strong></p>

<br/>
<p><a name="1974" id="1974"></a><img src="/biography/1974-1982.gif" alt="1974 - 1982" width="118" height="25" /></p>
<p><a href="/biography/photos/14.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/14tn.jpg" alt="avec Ya&ecirc;l Brandeis" width="100" height="82" /></a>Andr&eacute; Perry conceived and designed <strong>LE STUDIO (Morin Heights)</strong> which he operated with his life and business partner <strong>Ya&euml;l Brandeis</strong>.&nbsp; Tucked in the Laurentian Mountains, 65 Km from Montreal, Le Studio was created based on a revolutionary concept, defeating acoustic rules, blending creativity with technology.&nbsp; Not only was it located outside the metropolitan area, it was daringly far from the mainstream global music centers.&nbsp; Le Studio was the <a href="/biography/photos/13.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/13tn.jpg" alt="Complexe Le Studio" width="100" height="80" /></a></strong>first refined &lsquo;environmental recording studio&rsquo; in <a href="/biography/photos/12.jpg"><strong></strong></a>which artists were embedded for the duration of the recording process, which sometimes lasted more than 4 months, in an atmosphere of creative protection and encouragement.</p>

<p><a href="/biography/photos/20.jpg" class="FloatLeft"><img src="/biography/photos/20tn.jpg" alt="SSL Console" width="100" height="50" /></a><a href="/biography/photos/15.jpg"></a>Recognizing the superiority of the Solid State Logic Mastersystem (SSL) console Le Studio and London&rsquo;s Abbey Road Studios were the first in the world to put it to use. Perry&rsquo;s subsequent input through constant dialogue with the manufacturer was always appreciated and <a href="/biography/photos/15.jpg" class="FloatRight"><img src="/biography/photos/15tn.jpg" alt="Le Studio" width="100" height="63" /></a>frequently integrated in future versions.&nbsp; The SSL console is still considered the world&rsquo;s finest. In keeping with Perry&rsquo;s tradition, Le Studio was the earliest to introduce the digital recorder, (the two channel JVC BP90) using it first on the Police Synchronicity album.</p>
<p><a href="/biography/photos/16.jpg" class="FloatLeft"><img src="/biography/photos/16tn.jpg" alt="avec Cat Stevens" width="100" height="80" /></a>Perry&rsquo;s philosophy of nurturing the artists and musicians, as well as his personnel, redefined the studio industry, bringing to an end the era of dark, closed&ndash;in studio settings and transforming the approach to recording studio design. Rather than (as was the norm) imposing its own sound characteristics, stamping its own identity on the recordings, the studio&rsquo;s flexibility and distinctive combination of European and North American equipment made it a versatile and sophisticated instrument, servicing the individual sound and core of each artist.&nbsp; </p>
<p><a href="/biography/photos/17.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/17tn.jpg" alt="Rush" width="100" height="80" /></a>The world-class music complex quickly attracted and became favorite of many international clients, including (alphabetically<strong>) </strong><strong>April Wine, ASIA, Bryan Adams, the Bee Gees, David Bowie, Cat Stevens, Chicago, Julien Clerc, Roberta Flack, Corey Hart, Ian Hunter, Catherine Lara, Kim Mitchell, Nazareth, the Police, Keith Richards, Rush, Sting, Toronto</strong>.&nbsp; The quality of the <a href="/biography/photos/18.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/18tn.jpg" alt="with Sting" width="100" height="68" /></a>facility and of its clients earned it - together with <strong>George Martin&rsquo;s Air Montserrat</strong> - the position of best recording studio in the world, named in the industry&rsquo;s leading magazine, Pro Sound News&rsquo; annual Recording &amp; Sound Awards.</p>
<br/><p><a href="/biography/photos/19.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/19tn.jpg" alt="avec The Bee Gees" width="100" height="83" /></a>With Ya&euml;l Brandeis looking after the day-to-day operations of the studio, Perry continued to produce and record a diverse list of established and new artists, as well as to encourage young local artists by donating studio time and advice.&nbsp; He was also member of the board of directors of Canadian Independent Record Production Association (CIRPA) and founding member of the Association Qu&eacute;b&eacute;coise de l&rsquo;Industrie du Disque, du Spectacle et de la Vid&eacute;o&nbsp; (L&rsquo;ADISQ) and of the CIRPA/L&rsquo;ADISQ alliance.</p>
<table width="100%" border="0" cellpadding="10">
	<tr>
		<td align="left"><a href="/biography/photos/Artist3.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist3.jpg" alt="" width="100" height="66" /></a></td>
		<td align="left"><a href="/biography/photos/Artist5.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist5.jpg" alt="" width="100" height="66" /></a></td>
		<td align="left"><a href="/biography/photos/Artist6.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist6.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
	<tr>
		<td align="left"><a href="/biography/photos/Artist7.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist7.jpg" alt="" width="100" height="66" /></a></td>
		<td align="left"><a href="/biography/photos/Artist8.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist8.jpg" alt="" width="100" height="66" /></a></td>
		<td align="left"><a href="/biography/photos/Artist9.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist9.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
	<tr>
		<td align="left"><a href="/biography/photos/Artist10.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist10.jpg" alt="" width="100" height="66" /></a></td>
		<td align="left"><a href="/biography/photos/Artist11.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist11.jpg" alt="" width="100" height="66" /></a></td>
		<td align="left"><a href="/biography/photos/Artist4.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist4.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
</table>
<p align="center">&nbsp;</p>
<p><a name="1982" id="1982"></a><img src="/biography/1982-1988.gif" alt="1982-1988" width="118" height="25" /></p>
<p><a href="/biography/photos/21.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/21tn.jpg" alt="Salle de contr&ocirc;le vid&eacute;o" width="100" height="71" /></a>Inspired by Ron Hayes&rsquo; electronic visual of Richard Wagner&rsquo;s <em>Tristan &amp; Isolde</em>, and anticipating&nbsp; the video evolution, Andr&eacute; Perry diversified and expanded Le Studio, adding <strong>Andr&eacute; Perry Video</strong>.&nbsp; The result was one of the most avant-garde video facilities of its time; with a computer graphics department and an electronic music studio complementing the editing suites and shooting stage.&nbsp; During the following years, the Video facility was involved in the production of television specials for the American and Canadian networks including The World Challenge series starring Peter Ustinov, specials starring violinist Itzhak Perlman, the Montreal Symphony Orchestra, Nancy Reagan, Barbara Walters, industrial videos for SNC Lavalin and for the Kennedy Center, electronic signatures &amp; show openings for <a href="/biography/photos/22.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/22tn.jpg" alt="R&eacute;ception Studio Washington" width="100" height="67" /></a>Radio Canada&rsquo;s annual &lsquo;<em>Bye &lsquo;Bye</em> &amp; &lsquo;<em>Les Beaux Dimanches</em>&rsquo;, NBC&rsquo;s NFL openings and the Bill Cosby show opening for CBS, as well as numerous music videos and television commercials.</p>
<p>
<p>&nbsp;</p>
<a href="/biography/photos/23.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/23tn.jpg" alt="Film transfer room" width="100" height="67" /></a>In 1986 Le Studio and Andr&eacute; Perry Video made a public offering on the Montreal Stock Exchange, changing the name to <strong>Group Andr&eacute; Perry Inc</strong>.&nbsp; The company grew, building a similar facility in Washington D.C. and acquiring two video and computer-graphic facilities; one in San Francisco the other in Silicon Valley.&nbsp; The following year the company raised $25,000,000.00 through a Swiss convertible bond issue to further its development.
</p>
<p><a name="1988" id="1988"></a><img src="/biography/1988-today_en.gif" alt="1988 &ndash; present" width="90" height="41" /></p>
<p>Andr&eacute; Perry C.M. is presently President and founding partner of Fidelio Technologies Inc.  <a target="_blank" href="http://www.2xhd.com">www.2xHD.com</a>.</p>
<p align="center"><a style="margin-bottom:10px;" href="/biography/photos/andre-new-bigger.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/andre-new.jpg" alt="Andre Perry and Le Studio" width="100" height="75" border="2" /></a><a style="margin-bottom:10px;" href="/biography/photos/36.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/36tn.jpg" alt="Andre Perry et Ya&ecirc;l Brandeis 2006" width="100" height="75" border="2" /></a></p>
<br clear="all" />
<h2 id="contact-info" style="margin-bottom:15px">Contact Information</h2>
<p><strong>Email:</strong> ynaperry@hotmail.com</p>
<br clear="all" />
';
?>
