<?php
$MenuBio = "Biographie";
$MenuDisco = "Discographie";
$MenuAwards = "Prix & Affiliation";
$MenuContact = "Contact";
$PageTitle = 'Biographie';
$PageDescription = "Biographie d'Andre Perry :: Créateur du Studio (Morin-Heights), premier studio d'enregistrement à l&rsquo;équipement perfectionné de calibre mondial installé dans un environnement propice à la créativité et largement reconnu comme l'un des membres les plus importants de l'industrie canadienne de la musique";
$PageKeywords = 'Andre Perry, Biographie Andre Perry, Andre Perry studio, le studio, normedia';
//
$PageContent = '
<p><a href="/biography/photos/present-andre.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/present-andre-tb.jpg" alt="Andre Perry Ca. 1956" width="100" height="92" /></a>Andr&eacute; Perry est le pr&eacute;sident et associ&eacute; fondateur de Fidelio Technologies Inc. <a target="_blank" href="http://www.fideliotechnologies.com">www.fideliotechnologies.com</a>.  Cette soci&eacute;t&eacute; a d&eacute;velopp&eacute; le 2xHD, un syst&egrave;me exclusif pour le transfert de matri&ccedil;age (mastering) avec l&rsquo;encodage DSD des bandes maitresses sur ruban en format audionum&eacute;rique de haute r&eacute;solution DXD et d&eacute;rivatives 88/24 et plus, permettant le t&eacute;l&eacute;chargement sur les sites audio Haut D&eacute;finition dans le monde entier, et ce, sans compression et avec une fid&eacute;lit&eacute; nettement sup&eacute;rieure que le CD. Fidelio Technologies offre &eacute;galement des contrats de concession de licence pour t&eacute;l&eacute;chargement.</p>
	<a href="/biography/photos/Andre_Perry-1956.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/Andre_Perry-1956.jpg" alt="Andre Perry Ca. 1956" width="100" height="66" /></a>
	<p>Pilier de l&rsquo;industrie de la production de disques, le parcours d&rsquo;Andr&eacute; Perry a pris son d&eacute;part dans le monde du jazz d&rsquo;o&ugrave; il a &eacute;volu&eacute; comme batteur, musicien de studio et auteur-compositeur, le menant aux rôles de r&eacute;alisateur et ing&eacute;nieur de son jusquà la conception de son propre studio.</p>
<p>Andr&eacute; Perry est le cr&eacute;ateur du complexe d&rsquo;enregistrement d&rsquo;envergure internationale Le Studio (Morin Heights). Il s&rsquo;agit du premier studio qui a su combiner des techniques de pointe &rsquo; un environnement loin des centres urbains o&ugrave; les artistes &eacute;taient pris en charge. Il s&rsquo;agit d&rsquo;un concept r&eacute;volutionnaire o&ugrave; se rencontrent la cr&eacute;ativit&eacute; des musiciens et l&rsquo;innovation technologique. Ainsi, Le Studio Morin-Heights est rapidement devenu le lieu de production d&rsquo;un club s&eacute;lect international qui regroupe des musiciens exceptionnels dont Sting, Rush, Bryan Adams, Keith Richards, ASIA, the Bee Gees, David Bowie, Cat Stevens, Chicago, Roberta Flack, The Police, et de nombreux autres, desquels la somme globale d&rsquo;enregistrements, ont vendu plus 250,000,000 exemplaires à travers le monde.</p>
<h2><a name="1960" id="1960"></a><img src="/biography/1960-1970.gif" alt="1960 - 1970" width="118" height="25" /></h2>
<p><a href="/biography/photos/3.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/3tn.jpg" alt="Ca. 1962" width="100" height="73" /></a><a href="/biography/photos/4.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/4tn.jpg" alt="1967 - Studio d&rsquo;enregistrement" width="100" height="73" /></a>Perry ouvrit son premier studio d&rsquo;enregistrement - Studio Andr&eacute; Perry - en 1962, dans la banlieue montr&eacute;alaise de Ville Brossard. </p>
<p><a href="/biography/photos/5.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/5tn.jpg" alt="Andre Perry :: Jean-Pierre Ferland" width="100" height="73" /></a>Dès  les toutes premi&egrave;res ann&eacute;es, la passion de Perry pour l&rsquo;excellence attire la  plupart des artistes qu&eacute;b&eacute;cois à son studio. Sa contribution importante aux  d&eacute;buts de carri&egrave;re de certains de ceux qui allaient devenir les chefs de file  de cette industrie naissante contribua &rsquo; sa r&eacute;putation&nbsp;; les disques  signature <em><strong>Jaune</strong></em> et <em><strong>Soleil</strong></em> qui allaient  confirmer la carri&egrave;re de <strong>Jean-Pierre Ferland</strong> sont r&eacute;alis&eacute;s et enregistr&eacute;s par Perry et sont encore consid&eacute;r&eacute;s comme des  jalons importants de la musique qu&eacute;b&eacute;coise. En f&eacute;vrier 2008, dans un sondage  men&eacute; par le grand journal <strong>La Presse</strong> de Montr&eacute;al visant à d&eacute;terminer  quels &eacute;taient les meilleurs disques qu&eacute;b&eacute;cois produits au cours des 50  dernières ann&eacute;es, les disques <strong><em>Jaune</em></strong> de <strong>Ferland</strong> et <strong><em>Lindbergh</em></strong>, de <strong>Robert Charlebois</strong>, qui avait aussi &eacute;t&eacute;  r&eacute;alis&eacute; et enregistr&eacute; par Perry à la même &eacute;poque, se m&eacute;ritèrent les première et  deuxième places respectivement. Un sondage similaire men&eacute; plus tôt par  l&rsquo;hebdomadaire culturel montr&eacute;alais <strong>Voir</strong> &eacute;tait arriv&eacute; aux mêmes  r&eacute;sultats.</p>
<p><a href="/biography/photos/5b.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/5btn.jpg" alt="Premi&egrave;re console num&eacute;rique" width="100" height="70" /></a><a href="/biography/photos/6.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/6tn.jpg" alt="Magn&eacute;tophones (Le Moog)" width="100" height="60" /></a>Toujours &agrave; la recherche de nouveaux horizons et des techniques les plus r&eacute;centes, Perry est le premier au Canada &agrave; utiliser dans son studio les appareils les plus modernes&nbsp;: une console &agrave; transistors, le premier synth&eacute;tiseur (le <strong>Moog</strong>), les premiers magn&eacute;tophones multipistes, etc. Son innovation et sa r&eacute;putation en font le choix tout indiqu&eacute; pour des projets sp&eacute;ciaux, et c&rsquo;est pourquoi aussi bien le gouvernement du Canada que celui du Qu&eacute;bec choisissent Perry pour r&eacute;aliser les pr&eacute;sentations multim&eacute;dia de leurs pavillons respectifs &agrave; l&rsquo;Expo &rsquo;67. Le Comit&eacute; organisateur des Jeux olympiques<strong> </strong>(COJO) lui demande de r&eacute;aliser la musique des c&eacute;r&eacute;monies d&rsquo;ouverture et de cl&ocirc;ture des <strong>Jeux olympiques de Montr&eacute;al en 1976</strong>. Les <strong>Grands Ballets Canadiens</strong> font appel &agrave; lui pour cr&eacute;er un environnement de pr&eacute;sonorisation (<em>playback</em>) multipiste pour leur interpr&eacute;tation de l&rsquo;op&eacute;ra rock<em> Tommy</em> des Who &agrave; la Place des Arts de Montr&eacute;al et le chor&eacute;graphe <strong>Eddy Toussaint</strong> lui confie la composition et la r&eacute;alisation de musique &eacute;lectronique originale pour sa compagnie de ballet. </p>
<p><a href="/biography/photos/LENNON-4.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/LENNON-41.jpg" alt="John Lennon single" width="100" height="94" /></a>
<p>En 1969, <strong>John Lennon</strong> et <strong>Yoko Ono</strong> viennent à Montréal et invitent la plan&egrave;te à leur &rsquo;Bed-in&rsquo; pour la Paix. Le dernier jour, on demande à Perry d&rsquo;enregistrer la chanson qui allait devenir un hymne des plus c&eacute;l&eacute;bres&eacute;: <strong>Give Peace a Chance</strong>. Pour remercier Perry de ses ajouts à la postproduction et de son talent dans le mixage final, Lennon ajouta g&eacute;n&eacute;reusement l&rsquo;adresse compl&egrave;te de Perry sur l&rsquo;&eacute;tiquette du disque, geste qui ne se faisait pas (et ne s&rsquo;est jamais refait). Au printemps 2009, à l&rsquo;occasion du 40e anniversaire de l&rsquo;événement, le <strong>Mus&eacute;e des beaux-arts de Montr&eacute;al</strong>, avec la collaboration de Yoko Ono, rappela le happening en présentant une exposition qui remporta un vif succès et qui pr&eacute;sentait des souvenirs du &rsquo;bed-in&rsquo; et de l&rsquo;enregistrement, des m&eacute;moires et des oeuvres d&rsquo;art de Yoko et des contributions de Perry. L&rsquo;exposition attira un nombre record de visiteurs. </p>
<table width="100%" border="0" cellpadding="10">
	<tr>
		<td align="center"><a href="/biography/photos/7.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/7tn.jpg" alt="Enregistrement de Give Peace a Chance de John Lennon" width="100" height="71" /></a></td>
		<td align="center"><a href="/biography/photos/Yoko Montreal_096[1].JPG" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Yoko-Montreal_096_tn.jpg" alt="" width="100" height="71" /></a></td>
		<td align="center"><a href="/biography/photos/John_Lennon-Yoko_Ono.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/John_Lennon-Yoko_Ono.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
	
</table>
<h2><a name="1970" id="1970"></a><img src="/biography/1970-1974.gif" alt="1970-1974" width="118" height="25" /></h2>
<p><a href="/biography/photos/8.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/8tn.jpg" alt="Studio-dans-l&rsquo;&eacute;glise" width="100" height="145" /></a><a href="/biography/photos/9.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/9tn.jpg" alt="Dans l&rsquo;&eacute;glise" width="100" height="67" /></a>
<p>Perry ach&egrave;te une &eacute;glise anglicane au carr&eacute; Amherst dans le centre de Montr&eacute;al et y d&eacute;m&eacute;nage son studio. Au d&eacute;but de 1970, bien avant l&rsquo;&egrave;re du num&eacute;rique, il persuade la multinationale Ampex Corp. de mettre au point et de fabriquer un syst&egrave;me de synchronisation permettant de r&eacute;unir plusieurs magn&eacute;tophones multipistes, pour doubler le nombre de pistes de 16 &agrave; 32.
</p>
<p><a href="/biography/photos/10.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/10tn.jpg" alt="Studio A" width="100" height="69" /></a>Perry vend le &quot;studio-dans-l&rsquo;&eacute;glise&quot; en 1972 pour se consacrer enti&egrave;rement &agrave; la r&eacute;alisation de disques et &agrave; la direction de sa nouvelle soci&eacute;t&eacute;, <a href="/biography/photos/11.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/11tn.jpg" alt="Ctrl. Room A" width="100" height="74" style="margin-top:8px"/></a><strong>Good Noise Records</strong>, et s&rsquo;associe &agrave; l&rsquo;effervescent milieu musical underground de New York en collaborant avec <strong>Tony Levin</strong>, <strong>David Spinozza, John Lissauer</strong> et<strong> </strong>les<strong> Brecker Brothers.</strong> Good Noise Records produit des disques de <strong>Alan Gerber, Anna McGarrigle, Ronney Abramson, Tim Ryan, Man Made, The Hotel Orchestra </strong>et<strong> Brian Blain.</strong></p>


<h2><a name="1974" id="1974"></a><img src="/biography/1974-1982.gif" alt="1974 - 1982" width="118" height="25" /></h2>
<p><a href="/biography/photos/14.jpg"></a><a href="/biography/photos/14.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/14tn.jpg" alt="avec Ya&ecirc;l Brandeis" width="100" height="82" /></a>Andr&eacute; Perry con&ccedil;oit et dessine <strong>LE STUDIO (Morin-Heights)</strong>, qu&rsquo;il exploite avec sa partenaire en affaires et dans la vie,<strong> Ya&euml;l Brandeis</strong>. Cach&eacute; dans les Laurentides, &agrave; 65&nbsp;km de Montr&eacute;al, <em>Le Studio</em> est fond&eacute; sur un concept r&eacute;volutionnaire, en repensant les principes de l&rsquo;acoustique, et en mariant cr&eacute;ativit&eacute; et technologie. Il n&rsquo;est pas seulement physiquement situ&eacute; &agrave; l&rsquo;ext&eacute;rieur de la r&eacute;gion m&eacute;tropolitaine, il contraste audacieusement avec les grands studios &quot;normaux&quot;. <em>Le Studio</em> <em><strong><em><strong><em><strong><a href="/biography/photos/13.jpg"></a></strong></em></strong></em></strong></em>est le premier studio &quot;d&rsquo;enregistrement environnemental&quot; <a href="/biography/photos/13.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/13tn.jpg" alt="Complexe Le Studio" width="100" height="80" /></a>perfectionn&eacute;, <a href="/biography/photos/12.jpg"><strong><em><strong><em><strong></strong></em></strong></em></strong></a>o&ugrave; les artistes vivent pendant tout la p&eacute;riode du processus d&rsquo;enregistrement, qui peut parfois durer plus de quatre mois, dans une atmosph&egrave;re de concentration et d&rsquo;encouragement propice &agrave; la cr&eacute;ation.<strong><a href="/biography/photos/13.jpg"><em><strong></strong></em></a></strong></p>
<p><a href="/biography/photos/20.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/20tn.jpg" alt="SSL Console" width="100" height="50" /></a>Devant l&rsquo;&eacute;vidente sup&eacute;riorit&eacute; de la console Mastersystem construite par Solid State Logic (SSL), <em>Le Studio</em> et les studios Abbey Road de Londres, ont &eacute;t&eacute; les premiers au monde &agrave; l&rsquo;adopter. Perry continuera par la suite des &eacute;changes r&eacute;guliers avec le fabricant et ses suggestions seront souvent incorpor&eacute;es dans les nouvelles versions. <a href="/biography/photos/15.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/15tn.jpg" alt="Le Studio" width="100" height="63" /></a>La console SSL est encore consid&eacute;r&eacute;e comme la meilleure au monde. Fid&egrave;le &agrave; ses habitudes, Perry a &eacute;t&eacute; le premier &agrave; installer au<em> Studio</em> un appareil d&rsquo;enregistrement num&eacute;rique (le JVC BP90 &agrave; deux voies), employ&eacute; pour la premi&egrave;re fois pour le disque<em> Synchronicity</em> du groupe The Police.</p>
<p><a href="/biography/photos/16.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/16tn.jpg" alt="avec Cat Stevens" width="100" height="80" /></a>La philosophie de Perry consistant &agrave; soutenir les artistes et les musiciens, sans parler de son personnel, apport un souffle nouveau &agrave; l&rsquo;industrie, marquant la fin de l&rsquo;&eacute;poque des studios sombres et ferm&eacute;s et transformant la mani&egrave;re de concevoir les studios d&rsquo;enregistrement. Au lieu d&rsquo;imposer ses propres caract&eacute;ristiques sonores, de marquer les enregistrements de sa propre identit&eacute; (ce qui &eacute;tait la norme jusque l&agrave;), la souplesse et le mariage distinctif de mat&eacute;riel europ&eacute;en et nord-am&eacute;ricain du <em>Studio</em> en faisait un instrument perfectionn&eacute; et adaptable, au service de la sonorit&eacute; et de la cr&eacute;ativit&eacute; de chacun des artistes. </p>
<p><a href="/biography/photos/17.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/17tn.jpg" alt="Rush" width="100" height="80" /></a>Le complexe musical de calibre mondial attira rapidement de nombreux clients internationaux qui se plaisaient &agrave; y revenir, parmi lesquels (en ordre alphab&eacute;tique)<strong> April Wine, ASIA, Bryan Adams, les Bee Gees, David Bowie, Cat Stevens, Chicago, Julien Clerc, Roberta Flack, Corey Hart, Ian Hunter, Catherine Lara, Kim Mitchell, Nazareth, The Police, Keith Richards, Rush, Sting, Toronto</strong>. La qualit&eacute; des <a href="/biography/photos/18.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/18tn.jpg" alt="with Sting" width="100" height="68" /></a>installations et de ses clients a m&eacute;rit&eacute; au <em>Studio</em> - ainsi qu&rsquo;au studio <strong>Air Montserrat </strong>de <strong>George Martin </strong>&ndash; le titre de meilleurs studios d&rsquo;enregistrement au monde de la part du grand magazine de la profession <em>Pro Sound News.</em> </p><br/>
<p><a href="/biography/photos/19.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/19tn.jpg" alt="avec The Bee Gees" width="100" height="83" /></a>Pendant que Ya&euml;l Brandeis dirige le fonctionnement quotidien du studio, Perry continue de r&eacute;aliser et d&rsquo;enregistrer les disques d&rsquo;artistes tr&egrave;s divers, certains bien connus, d&rsquo;autres moins, tout en soutenant de jeunes artistes locaux en leur pr&ecirc;tant gratuitement le studio de temps &agrave; autre et en leur prodiguant des conseils. Il a aussi &eacute;t&eacute; membre du conseil d&rsquo;administration de la <em>Canadian Independent Record Production Association</em> (CIRPA),membre fondateur de l&rsquo;<em>Association qu&eacute;b&eacute;coise de l&rsquo;industrie du disque, du spectacle et de la vid&eacute;o</em> (ADISQ), ainsi que de l&rsquo;alliance entre ces deux organismes. </p>
<table width="100%" border="0" cellpadding="10">
	<tr>
		<td align="center"><a href="/biography/photos/Artist3.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist3.jpg" alt="" width="100" height="66" /></a></td>
		<td align="center"><a href="/biography/photos/Artist5.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist5.jpg" alt="" width="100" height="66" /</a></td>
		<td align="center"><a href="/biography/photos/Artist6.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist6.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
	<tr>
		<td align="center"><a href="/biography/photos/Artist7.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist7.jpg" alt="" width="100" height="66" /></a></td>
		<td align="center"><a href="/biography/photos/Artist8.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist8.jpg" alt="" width="100" height="66" /></a></td>
		<td align="center"><a href="/biography/photos/Artist9.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist9.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
	<tr>
		<td align="center"><a href="/biography/photos/Artist10.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist10.jpg" alt="" width="100" height="66" /></a></td>
		<td align="center"><a href="/biography/photos/Artist11.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist11.jpg" alt="" width="100" height="66" /></a></td>
		<td align="center"><a href="/biography/photos/Artist4.jpg" class="photoframe" data-lightbox="roadtrip"><img src="/biography/photos/Artist4.jpg" alt="" width="100" height="66" /></a></td>
	</tr>
</table>
<p align="center">&nbsp;</p>
<p><a name="1982" id="1982"></a><img src="/biography/1982-1988.gif" alt="1982-1988" width="118" height="25" /></p>
<p><a href="/biography/photos/21.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/21tn.jpg" alt="Salle de contr&ocirc;le vid&eacute;o" width="100" height="71" /></a>Inspir&eacute; par l&rsquo;interpr&eacute;tation visuelle &eacute;lectronique de Ron Hayes du <em>Tristan et Isolde</em> de Richard Wagner, et pr&eacute;voyant la perc&eacute;e du vid&eacute;o, Andr&eacute; Perry diversifie et agrandit <em>Le Studio</em>, en y ajoutant <strong>Andr&eacute; Perry Vid&eacute;o</strong>. Il cr&eacute;e ainsi l&rsquo;un des ateliers vid&eacute;o les plus avant-gardiste de l&rsquo;&eacute;poque, avec un service d&rsquo;infographie et un studio de musique &eacute;lectronique pour appuyer les salles de montage et le plateau de tournage. Au cours des ann&eacute;es qui suivent, l&rsquo;atelier vid&eacute;o participe &agrave; <a href="/biography/photos/22.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/22tn.jpg" alt="R&eacute;ception Studio Washington" width="100" height="67" /></a>la production d&rsquo;&eacute;missions sp&eacute;ciales de t&eacute;l&eacute;vision pour des r&eacute;seaux am&eacute;ricains et canadiens, notamment la s&eacute;rie <em>The World Challenge</em> mettant en vedette Peter Ustinov, des sp&eacute;ciaux avec le violoniste Itzhak Perlman, l&rsquo;Orchestre symphonique de Montr&eacute;al, Nancy Reagan, Barbara Walters, des vid&eacute;os industriels pour SNC-Lavalin et pour le Centre Kennedy, des indicatifs visuels &eacute;lectroniques pour les <em>Bye Bye</em> annuels et <em>Les Beaux Dimanches</em> de Radio-Canada, des s&eacute;quences d&rsquo;ouverture pour la retransmission de la NFL &agrave; NBC, pour le <em>Bill Cosby Show</em> &agrave; CBS, en plus de nombreux vid&eacute;os de musique et commerciaux de t&eacute;l&eacute;vision.</p>
<p><a href="/biography/photos/23.jpg" class="FloatRight" data-lightbox="roadtrip"><img src="/biography/photos/23tn.jpg" alt="Film transfer room" width="100" height="67" /></a>En 1986, <em>Le Studio</em> et <em>Andr&eacute; Perry Vid&eacute;o</em> lancent une offre publique &agrave; la Bourse de Montr&eacute;al, sous le nom de <strong>Groupe Andr&eacute; Perry Inc</strong>. L&rsquo;entreprise grandit et &eacute;tablit une installation du m&ecirc;me calibre &agrave; Washington (D.C.) et fait l&rsquo;acquisition de deux maisons de vid&eacute;o et d&rsquo;infographie, l&rsquo;une &agrave; San Francisco et l&rsquo;autre &agrave; Silicon Valley. L&rsquo;ann&eacute;e suivante, la soci&eacute;t&eacute; r&eacute;unit 25&nbsp;M$ par l&rsquo;&eacute;mission d&rsquo;obligations convertibles en Suisse pour poursuivre sa croissance.</p>
<p><a name="1988" id="1988"></a><img src="/biography/1988-today_fr.gif" alt="1988 &ndash; maintenant" width="128" height="23" /></p>
<p>Andr&eacute; Perry est pr&eacute;sident et, avec Ren&eacute; Laflamme, co-fondateur/partenaire de Fidelio Technologies Inc. <a target="_blank" href="http://www.fideliotechnologies.com">www.fideliotechnologies.com</a></p>
<p align="center"><a style="margin-bottom:10px;" href="/biography/photos/andre-new-bigger.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/andre-new.jpg" alt="Andre Perry et Le Studio" width="100" height="75" border="2" /></a><a style="margin-bottom:10px;" href="/biography/photos/36.jpg" class="FloatLeft" data-lightbox="roadtrip"><img src="/biography/photos/36tn.jpg" alt="Andre Perry et Ya&ecirc;l Brandeis 2006" width="100" height="75" border="2" /></a></p>
<br clear="all" />
<h2 id="contact-info" style="margin-bottom:15px">Informations de contact</h2>
<p><strong>Courriel:</strong> ynaperry@hotmail.com</p>
<br clear="all" />
';
?>